[platformio]
default_envs = waveshare_esp32_s3_rlcd_4_2

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = espidf
monitor_speed = 115200
upload_speed = 460800
board_build.partitions = partitions.csv
extra_scripts = pre:scripts/platformio_solaros_flavor.py

[env:waveshare_esp32_s3_rlcd_4_2]
board = waveshare_esp32_s3_rlcd_4_2
board_build.cmake_extra_args = -DSOLAR_OS_BOARD=waveshare_esp32_s3_rlcd_4_2

[env:esp32_s3_devkitc1_n16r8]
board = esp32-s3-devkitc1-n16r8
board_build.cmake_extra_args = -DSOLAR_OS_BOARD=esp32_s3_devkitc1_n16r8

[env:m5stack_cardputer]
board = m5stack_cardputer
custom_solar_os_flavor = cardputer
monitor_dtr = 0
monitor_rts = 0
board_build.partitions = partitions_cardputer.csv
board_build.cmake_extra_args = -DSOLAR_OS_BOARD=m5stack_cardputer -DSDKCONFIG_DEFAULTS=sdkconfig.defaults;sdkconfig.cardputer.defaults
