#pragma once

#include "driver/gpio.h"
#include "driver/i2c_types.h"
#include "driver/i2s_types.h"
#include "driver/uart.h"

#define SOLAR_OS_BOARD_ID "waveshare_esp32_s3_rlcd_4_2"
#define SOLAR_OS_BOARD_NAME "Waveshare ESP32-S3-RLCD-4.2"
#define SOLAR_OS_BOARD_VENDOR "Waveshare"
#define SOLAR_OS_BOARD_MODULE_NAME "ESP32-S3-WROOM-1-N16R8"

#define SOLAR_OS_BOARD_CAPABILITIES \
    (SOLAR_OS_BOARD_CAP_PSRAM | \
     SOLAR_OS_BOARD_CAP_DISPLAY | \
     SOLAR_OS_BOARD_CAP_GFX | \
     SOLAR_OS_BOARD_CAP_CDC | \
     SOLAR_OS_BOARD_CAP_UART | \
     SOLAR_OS_BOARD_CAP_SD | \
     SOLAR_OS_BOARD_CAP_I2C | \
     SOLAR_OS_BOARD_CAP_RTC | \
     SOLAR_OS_BOARD_CAP_BATTERY | \
     SOLAR_OS_BOARD_CAP_AUDIO | \
     SOLAR_OS_BOARD_CAP_WIFI | \
     SOLAR_OS_BOARD_CAP_BLE | \
     SOLAR_OS_BOARD_CAP_GPIO | \
     SOLAR_OS_BOARD_CAP_ADC | \
     SOLAR_OS_BOARD_CAP_PWM | \
     SOLAR_OS_BOARD_CAP_KEY | \
     SOLAR_OS_BOARD_CAP_TEMPERATURE | \
     SOLAR_OS_BOARD_CAP_HUMIDITY)

#define SOLAR_OS_BOARD_DISPLAY_CONTROLLER "ST7305"
#define SOLAR_OS_BOARD_DISPLAY_WIDTH 400
#define SOLAR_OS_BOARD_DISPLAY_HEIGHT 300
#define SOLAR_OS_BOARD_DISPLAY_ROTATION_OFFSET 1

#define SOLAR_OS_BOARD_PIN_LCD_DC GPIO_NUM_5
#define SOLAR_OS_BOARD_PIN_LCD_CS GPIO_NUM_40
#define SOLAR_OS_BOARD_PIN_LCD_SCK GPIO_NUM_11
#define SOLAR_OS_BOARD_PIN_LCD_MOSI GPIO_NUM_12
#define SOLAR_OS_BOARD_PIN_LCD_RST GPIO_NUM_41
#define SOLAR_OS_BOARD_PIN_LCD_TE GPIO_NUM_6

#define SOLAR_OS_BOARD_I2C_PORT I2C_NUM_0
#define SOLAR_OS_BOARD_PIN_I2C_SDA GPIO_NUM_13
#define SOLAR_OS_BOARD_PIN_I2C_SCL GPIO_NUM_14

#define SOLAR_OS_BOARD_PIN_SDMMC_CLK GPIO_NUM_38
#define SOLAR_OS_BOARD_PIN_SDMMC_CMD GPIO_NUM_21
#define SOLAR_OS_BOARD_PIN_SDMMC_D0 GPIO_NUM_39

#define SOLAR_OS_BOARD_PIN_BATTERY_ADC GPIO_NUM_4
#define SOLAR_OS_BOARD_BATTERY_ADC_DIVIDER_RATIO 3.0f

#define SOLAR_OS_BOARD_I2S_PORT I2S_NUM_0
#define SOLAR_OS_BOARD_PIN_I2S_MCLK GPIO_NUM_16
#define SOLAR_OS_BOARD_PIN_I2S_BCLK GPIO_NUM_9
#define SOLAR_OS_BOARD_PIN_I2S_WS GPIO_NUM_45
#define SOLAR_OS_BOARD_PIN_I2S_DIN GPIO_NUM_10
#define SOLAR_OS_BOARD_PIN_I2S_DOUT GPIO_NUM_8
#define SOLAR_OS_BOARD_PIN_AUDIO_PA GPIO_NUM_46
#define SOLAR_OS_BOARD_AUDIO_CODEC_OUT "ES8311"
#define SOLAR_OS_BOARD_AUDIO_CODEC_IN "ES7210"

#define SOLAR_OS_BOARD_PIN_KEY GPIO_NUM_18
#define SOLAR_OS_BOARD_KEY_ACTIVE_LEVEL 0
#define SOLAR_OS_BOARD_KEY_PULL_UP 1
#define SOLAR_OS_BOARD_KEY_PULL_DOWN 0

#define SOLAR_OS_BOARD_EXPANSION_GPIO_MASK ((1ULL << GPIO_NUM_0) | \
                                            (1ULL << GPIO_NUM_1) | \
                                            (1ULL << GPIO_NUM_2) | \
                                            (1ULL << GPIO_NUM_3) | \
                                            (1ULL << GPIO_NUM_17) | \
                                            (1ULL << GPIO_NUM_18))
#define SOLAR_OS_BOARD_USER_GPIO_MASK ((1ULL << GPIO_NUM_1) | \
                                       (1ULL << GPIO_NUM_2) | \
                                       (1ULL << GPIO_NUM_3) | \
                                       (1ULL << GPIO_NUM_17))
#define SOLAR_OS_BOARD_EXPANSION_GPIO_LIST "0 1 2 3 17 18"
#define SOLAR_OS_BOARD_USER_GPIO_LIST "1 2 3 17"
#define SOLAR_OS_BOARD_GPIO_SLOTS { \
    {.pin = 0, .runtime_allowed = false, .role = "BOOT/download"}, \
    {.pin = 1, .runtime_allowed = true, .role = "expansion"}, \
    {.pin = 2, .runtime_allowed = true, .role = "expansion"}, \
    {.pin = 3, .runtime_allowed = true, .role = "expansion"}, \
    {.pin = 17, .runtime_allowed = true, .role = "expansion"}, \
    {.pin = 18, .runtime_allowed = false, .role = "KEY"}, \
}

#define SOLAR_OS_BOARD_UART_PORT UART_NUM_0
#define SOLAR_OS_BOARD_PIN_UART_TX GPIO_NUM_43
#define SOLAR_OS_BOARD_PIN_UART_RX GPIO_NUM_44

#define WS_RLCD_BOARD_NAME SOLAR_OS_BOARD_NAME
#define WS_RLCD_MODULE_NAME SOLAR_OS_BOARD_MODULE_NAME
#define WS_RLCD_DISPLAY_CONTROLLER SOLAR_OS_BOARD_DISPLAY_CONTROLLER
#define WS_RLCD_DISPLAY_WIDTH SOLAR_OS_BOARD_DISPLAY_WIDTH
#define WS_RLCD_DISPLAY_HEIGHT SOLAR_OS_BOARD_DISPLAY_HEIGHT
#define WS_RLCD_PIN_LCD_DC SOLAR_OS_BOARD_PIN_LCD_DC
#define WS_RLCD_PIN_LCD_CS SOLAR_OS_BOARD_PIN_LCD_CS
#define WS_RLCD_PIN_LCD_SCK SOLAR_OS_BOARD_PIN_LCD_SCK
#define WS_RLCD_PIN_LCD_MOSI SOLAR_OS_BOARD_PIN_LCD_MOSI
#define WS_RLCD_PIN_LCD_RST SOLAR_OS_BOARD_PIN_LCD_RST
#define WS_RLCD_PIN_LCD_TE SOLAR_OS_BOARD_PIN_LCD_TE
#define WS_RLCD_PIN_I2C_SDA SOLAR_OS_BOARD_PIN_I2C_SDA
#define WS_RLCD_PIN_I2C_SCL SOLAR_OS_BOARD_PIN_I2C_SCL
#define WS_RLCD_PIN_SDMMC_CLK SOLAR_OS_BOARD_PIN_SDMMC_CLK
#define WS_RLCD_PIN_SDMMC_CMD SOLAR_OS_BOARD_PIN_SDMMC_CMD
#define WS_RLCD_PIN_SDMMC_D0 SOLAR_OS_BOARD_PIN_SDMMC_D0
#define WS_RLCD_PIN_BATTERY_ADC SOLAR_OS_BOARD_PIN_BATTERY_ADC
#define WS_RLCD_BATTERY_ADC_DIVIDER_RATIO SOLAR_OS_BOARD_BATTERY_ADC_DIVIDER_RATIO
#define WS_RLCD_I2S_PORT SOLAR_OS_BOARD_I2S_PORT
#define WS_RLCD_PIN_I2S_MCLK SOLAR_OS_BOARD_PIN_I2S_MCLK
#define WS_RLCD_PIN_I2S_BCLK SOLAR_OS_BOARD_PIN_I2S_BCLK
#define WS_RLCD_PIN_I2S_WS SOLAR_OS_BOARD_PIN_I2S_WS
#define WS_RLCD_PIN_I2S_DIN SOLAR_OS_BOARD_PIN_I2S_DIN
#define WS_RLCD_PIN_I2S_DOUT SOLAR_OS_BOARD_PIN_I2S_DOUT
#define WS_RLCD_PIN_AUDIO_PA SOLAR_OS_BOARD_PIN_AUDIO_PA
#define WS_RLCD_AUDIO_CODEC_OUT SOLAR_OS_BOARD_AUDIO_CODEC_OUT
#define WS_RLCD_AUDIO_CODEC_IN SOLAR_OS_BOARD_AUDIO_CODEC_IN
#define WS_RLCD_PIN_KEY SOLAR_OS_BOARD_PIN_KEY
#define WS_RLCD_KEY_ACTIVE_LEVEL SOLAR_OS_BOARD_KEY_ACTIVE_LEVEL
#define WS_RLCD_KEY_PULL_UP SOLAR_OS_BOARD_KEY_PULL_UP
#define WS_RLCD_KEY_PULL_DOWN SOLAR_OS_BOARD_KEY_PULL_DOWN
#define WS_RLCD_EXPANSION_GPIO_MASK SOLAR_OS_BOARD_EXPANSION_GPIO_MASK
#define WS_RLCD_USER_GPIO_MASK SOLAR_OS_BOARD_USER_GPIO_MASK
#define WS_RLCD_UART_PORT SOLAR_OS_BOARD_UART_PORT
#define WS_RLCD_PIN_UART_TX SOLAR_OS_BOARD_PIN_UART_TX
#define WS_RLCD_PIN_UART_RX SOLAR_OS_BOARD_PIN_UART_RX
